### ISSUE TITLE
Multiple basis sets vs. simplified parser

### ISSUE THREAD

**Issue by OndrejMarsalek** [cp2k/cp2k-input-tools#32]
I came across a problem when using `CP2KInputParserSimplified` with multiple basis sets for an atomic kind (say, an ADMM calculation) and wanted to check if it is something that should be fixed, or if I need to use the full parser. Specifically, given the input snippet
```
&FORCE_EVAL
  &SUBSYS
    &KIND H
      POTENTIAL GTH-PBE-q1
      BASIS_SET TZV2P-MOLOPT-GTH
      BASIS_SET AUX_FIT pFIT3
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
```
and the code
```python
from cp2k_input_tools.parser import CP2KInputParserSimplified
tree = CP2KInputParserSimplified().parse(open('test-basis.inp'))
print(tree['force_eval']['subsys']['kind']['H'])
```
I get
```
{'potential': 'GTH-PBE-q1', 'basis_set': [['AUX_FIT', 'pFIT3'], ['AUX_FIT', 'pFIT3']]}
```
which is incorrect and also ends up with an incorrect input file when written using `CP2KInputGenerator`.

Adding an explicit `ORB` to the primary basis does not help, as it results in:
```
{'potential': 'GTH-PBE-q1', 'basis_set': ['ORB', 'TZV2P-MOLOPT-GTH', ['AUX_FIT', 'pFIT3']]}
```

Switching the order of the two lines changes the output to the still incorrect
```
{'potential': 'GTH-PBE-q1', 'basis_set': ['AUX_FIT', 'pFIT3', 'TZV2P-MOLOPT-GTH']}
```

On the other hand, `CP2KInputParser` processes it fine. Is this a bug or expected behavior for the simplified parser? If so, should it perhaps raise an exception instead? Thank you for looking at this.

**Comment by dev-zero** [comment]
Thanks for the bug report!
Well, it's definitely a bug: if something could not be parsed correctly it should have raised an exception at least, but the first one is wrong as it should give:

```python
{'potential': 'GTH-PBE-q1', 'basis_set': [('ORB', 'TZV2P-MOLOPT-GTH'), ('AUX_FIT', 'pFIT3')]}
```

or

```python
{'potential': 'GTH-PBE-q1', 'basis_set': ['TZV2P-MOLOPT-GTH', ('AUX_FIT', 'pFIT3')]}
```

**Comment by OndrejMarsalek** [comment]
Thanks for the confirmation. Let me know if I can provide more information or do some testing.

**Comment by dev-zero** [comment]
> Thanks for the confirmation. Let me know if I can provide more information or do some testing.

Thanks :) updated v0.6.1 with a fix pushed to PyPI, but might take a couple of minutes more until it is distributed.

**Comment by OndrejMarsalek** [comment]
Thank you for the speedy fix! Unfortunately, it looks like it still does not work correctly if the lines are switched. This input:
```
&FORCE_EVAL
  &SUBSYS
    &KIND H
      POTENTIAL GTH-PBE-q1
      BASIS_SET AUX_FIT pFIT3
      BASIS_SET TZV2P-MOLOPT-GTH
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
```
results in
```
{'potential': 'GTH-PBE-q1', 'basis_set': ['AUX_FIT', 'pFIT3', 'TZV2P-MOLOPT-GTH']}
```
while adding `ORB` gives
```
{'potential': 'GTH-PBE-q1', 'basis_set': ['AUX_FIT', 'pFIT3', ['ORB', 'TZV2P-MOLOPT-GTH']]}
```

**Comment by dev-zero** [comment]
Ok, I see.

**Comment by dev-zero** [comment]
Ok, another fix is out. Thanks!

**Comment by OndrejMarsalek** [comment]
Looks good, thank you!
